spring:
  datasource:
    url:
    username: sa
    password: sa
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        ddl-auto: create-drop
  h2:
    console:
      enabled: true

loggin:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: true
